### ISSUE TITLE
IE < 9 complains about addEventListener

### ISSUE THREAD

**Issue by adammessinger** [scottjehl/iOS-Orientationchange-Fix#10]
IE < 9 throws a JS error since it doesn't support this method. This can be fixed -- and the script can be exited early on all desktop browsers -- by changing line 8 from this:

``` javascript
if( !doc.querySelector ){ return; }
```

to this:

``` javascript
if( !doc.querySelector || w.orientation === undefined ){ return; }
```

Another approach would be to use UA sniffing, as suggested in issue #4. This is one of those rare cases where I think it might be a better idea than feature detection.

**Comment by scottjehl** [comment]
There's a UA sniff in there now, so closing this out. thanks!
