### ISSUE TITLE
iPhone + <select> zooms page

### ISSUE THREAD

**Issue by dirtystylus** [scottjehl/iOS-Orientationchange-Fix#12]
Testing this I found an interesting side effect to this script on iPhone/iPod touch hardware. When a <select> element is added to the page, triggering the select to display the options causes the page to zoom. Rotating to landscape orientation zooms further.

Here’s a test page:

http://dirtystylus.com/sandbox/iosorientation/index.html

Compare to a version using the orientation fix by Jeremy Keith:

http://dirtystylus.com/sandbox/iosorientation/adactio.html

In the adactio version the page doesn’t zoom when the select element is triggered.

The select widget doesn’t trigger a zoom on either version when using the iPad.

**Comment by scottjehl** [comment]
Thanks for the report. I think what you're reporting though, is just the default behavior on iOS when user scaling is enabled. If you turn off JS you should see the same thing.

Having scaling enabled at most times is the difference between this script and Jeremy's original approach, and you'll see other iOS default behavior when zoom is enabled, select and input zooming are part of that.

I agree this behavior isn't often desirable, but I'm not sure that this particular script should work around it.

For jQuery Mobile, I've implemented a more generic zoom managing utility that ends up being used for a few things, such as this orientation change bug, and also preventing zoom for select menus and inputs.

Maybe I could rework this script a bit to abstract out the zoom utility part and use it for a couple of external zoom fixes, which you could include separately.

Anyway, I'm going to close this out as it's unrelated to this particular script, and I'll give some thought to reworking this as more of a zoom utility.

Thanks!
