### ISSUE TITLE
GPL compatible license? 

### ISSUE THREAD

**Issue by krisbulman** [scottjehl/iOS-Orientationchange-Fix#19]
Any hope in dual licensing this as MIT & GPL? (like eCSSential)

**Comment by scottjehl** [comment]
Sure. That's what I typically use anyway.
On Jun 25, 2012 5:26 AM, "Kris Bulman" <
reply@reply.github.com>
wrote:

**Comment by krisbulman** [comment]
Great! Thanks for the quick reply, I will watch for the license update.
