### ISSUE TITLE
Causes error in iOS5

### ISSUE THREAD

**Issue by sirreal** [scottjehl/iOS-Orientationchange-Fix#26]
I was presented with a bug on a site and I tracked it down to this script. It uses the current minified src provided in this repo. The following error is thrown (copied from the ios5 safari debug console):

```
JavaScript: Error
undefined
TypeError: 'undefined' is not an object
```

This happens on iOS 5.1.1, 1st gen iPad.

**Comment by bigflannel** [comment]
Odd timing, but I just hit the same issue. Safari, and Chrome, on iPad 1st gen, iOS5.1.1.

**Comment by sirreal** [comment]
After some more investigation, it seems that the problem is that the code was wrapped in `jQuery(document).ready(...)`. When I pulled the code out let it execute at top level, no more error.

@bigflannel If this fixes your error, I'll close the issue.

**Comment by bigflannel** [comment]
Will not get chance to check until later today. But will update you when I have. Thanks for posting your solution.

**Comment by bigflannel** [comment]
Same here. When I put it on the top level there is no error. Thanks @SirReal.
