### ISSUE TITLE
Not working on iOS 4/3 on iPod Touch

### ISSUE THREAD

**Issue by ChristoDeluxe** [scottjehl/iOS-Orientationchange-Fix#7]
I've found this doesn't work on iPod Touch 2nd gen (iOS 4.2.1) and 1st gen (iOS 3.1.3).  Verified with my own app, as well as your test page.

It does work very well on iPhone 4S and iPod Touch 4th gen that are both running iOS 5.0.1.

Do any of those device orientation callbacks require a gyroscope?

**Comment by ChristoDeluxe** [comment]
Oh yes, deviceorientation requires a gyroscope, according to Apple.  iPod Touch 4th gen has a gyroscope, so it works there.

http://developer.apple.com/library/safari/#documentation/SafariDOMAdditions/Reference/DeviceOrientationEventClassRef/DeviceOrientationEvent/DeviceOrientationEvent.html

**Comment by ChristoDeluxe** [comment]
The code on the older-iOS-support branch works well on iOS 4

**Comment by scottjehl** [comment]
This should be good now. let me know if you run into more issues!
