### ISSUE TITLE
Doesn't work on iPhone 3GS running iOS 5.0.1

### ISSUE THREAD

**Issue by curtisj44** [scottjehl/iOS-Orientationchange-Fix#8]
The bug still exists when switching from portrait to landscape on an iPhone 3GS running iOS 5.0.1.

(This fix works on an iPhone 4 running iOS 5.0.1 though)

**Comment by adammessinger** [comment]
I believe this is because the fix requires a gyroscope and the 3GS just has an accelerometer.

**Comment by curtisj44** [comment]
This isn't an issue anymore with the latest version.
